/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.14
 * Generated at: 2025-11-17 07:25:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1763364228819L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1763364195663L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <title>K-INDIE</title>\r\n");
      out.write("  <link rel = \"stylesheet\" href=\"css/styles.css\"/>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header class=\"navbar\">\r\n");
      out.write("  <div class=\"navbar-inner\">\r\n");
      out.write("    <div class=\"navbar-logo\">K-<span>INDIE</span></div>\r\n");
      out.write("    <div class=\"navbar-menu\">\r\n");
      out.write("      <a href=\"index.jsp\" class=\"active\">Home</a>\r\n");
      out.write("      <a href=\"discover.jsp\">Discover</a>\r\n");
      out.write("      <a href=\"events.jsp\">Events</a>\r\n");
      out.write("      <a href=\"guide.jsp\">K-Indie 101</a>\r\n");
      out.write("      <a href=\"kIndieMap.jsp\">Map of K-Indie</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Language selector -->\r\n");
      out.write("    <div class=\"navbar-langSelect\">\r\n");
      out.write("      <button onclick=\"setLang('en')\">EN</button>\r\n");
      out.write("      <button onclick=\"setLang('ko')\">KO</button>\r\n");
      out.write("      <button onclick=\"setLang('jp')\">JP</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 햄버거 버튼 -->\r\n");
      out.write("    <a href=\"#\" class=\"navbar-togglebtn\">\r\n");
      out.write("      <i class=\"fa-solid fa-bars\" style=\"color: #1db954;\"></i>\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("  <main class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Hero Section -->\r\n");
      out.write("    <section class=\"hero\">\r\n");
      out.write("      <p class=\"breadcrumb\" data-i18n=\"index.breadcrumb\">Home</p>\r\n");
      out.write("      <h1><span data-i18n=\"index.heroTitle\">Dive into <br>Korean indie vibes</span></h1>\r\n");
      out.write("      <a href=\"https://youtu.be/MIrTYB99bcE?feature=shared\"\r\n");
      out.write("         class=\"btn-outline\"\r\n");
      out.write("         data-i18n=\"index.start\">Start Exploring</a>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Features Section -->\r\n");
      out.write("    <section class=\"features\">\r\n");
      out.write("      <div class=\"feature\">\r\n");
      out.write("        <h3 data-i18n=\"index.discover\">Discover</h3>\r\n");
      out.write("        <p data-i18n=\"index.discover.desc\">Explore a curated selection of indie artists and their music.</p>\r\n");
      out.write("        <a href=\"discover.jsp\">View More</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"feature\">\r\n");
      out.write("        <h3 data-i18n=\"index.events\">Events</h3>\r\n");
      out.write("        <p data-i18n=\"index.events.desc\">Find upcoming shows, gigs, and festivals featuring indie talent.</p>\r\n");
      out.write("        <a href=\"events.jsp\">View More</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"feature\">\r\n");
      out.write("        <h3 class=\"highlight\" data-i18n=\"index.guide\">K-Indie 101</h3>\r\n");
      out.write("        <p data-i18n=\"index.guide.desc\">Learn about the vibrant world of Korean indie music.</p>\r\n");
      out.write("        <a href=\"guide.jsp\">View More</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"feature\">\r\n");
      out.write("        <h3 data-i18n=\"index.map\">Map of K-Indie Clubs</h3>\r\n");
      out.write("        <p data-i18n=\"index.map.desc\">Join discussions and connect with fellow indie music fans.</p>\r\n");
      out.write("        <a href=\"kIndieMap.jsp\">View More</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"illustration-section\"\r\n");
      out.write("             style=\"padding: 10px 0; display: flex; justify-content: center;\">\r\n");
      out.write("      <img src=\"images/mainPage/bg.png\"\r\n");
      out.write("           alt=\"Korean indie illustration\"\r\n");
      out.write("           style=\"max-width: 100%; border-radius: 16px;\" />\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("   </main>\r\n");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("  <div class=\"footer-contents\">\r\n");
      out.write("    <p>© 2025 정대원 All rights reserved.</p>\r\n");
      out.write("    <p>\r\n");
      out.write("      <i class=\"fa-solid fa-envelope\" style=\"color: #1db954;\"></i>\r\n");
      out.write("      Contact  : daewon6905@gmail.com\r\n");
      out.write("    </p>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
